version: '3.8'

services:
  airplane-mcp-server:
    build: .
    image: airplane-mcp:latest
    container_name: airplane-mcp-server
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    # Uncomment for logging
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3"